apiVersion: batch/v1
kind: Job
metadata:
  name: model-train
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: model-train
        image: model-train:default
      	volumeMounts:
      	- mountPath: /model
      	  name: mount
      volumes:
      	- name: model-mount
      	  hostPath: 
      	   path: /tmp
      	   type: Directory
      restartPolicy: OnFailure
     
