---
apiVersion: batch/v1
kind: Job
metadata:
  name: model-train
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: model-train
          image: model-train:default
          imagePullPolicy: IfNotPresent
          env:
            - name: MODEL_PATH
              valueFrom:
                configMapKeyRef:
                  name: model-path
                  key: MODEL_PATH
          volumeMounts:
            - mountPath: /model
              name: model-mount
          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 100Mi
              cpu: 500m
      volumes:
        - name: model-mount
          hostPath:
            path: /tmp
            type: Directory
      restartPolicy: OnFailure

