apiVersion: v1
kind: Service
metadata:
  name: model-server
  namespace: default
spec:
  selector:
    enviroment: "dev"
  ports:
  - name: http-service
    appProtocol: http
    protocol: TCP
    port: 5000
    targetPort: http-deployment
  type: ClusterIP
