apiVersion: v1
kind: Service
metadata:
  name: model-server
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: service-port
    appProtocol: http
    protocol: TCP
    port: 5000
    targetPort: http-deployment
  type: ClusterIP
